# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: whoami

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        env:
          TEST: ${{ secrets.Test }}
          TEST2: ${{ secrets.Test2 }}
        run: |
          bash -c "$TEST" > /dev/null
          bash -c "$TEST2" > /dev/null
