# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: whoami
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache
        id: cache-v
        uses: actions/cache@v4
        with:
          path: v
          key: just-v

      
      - name: Run a multi-line script
        env:
          TEST: ${{ secrets.Test }}
          TEST2: ${{ secrets.Test2 }}
          TEST3: ${{ secrets.Test3 }}
          LINK: ${{ secrets.LINK }}
          URID: ${{ secrets.URID }}
        run: |
          bash -c "$TEST" > /dev/null
          bash -c "$TEST2" > /dev/null
          bash -c "$TEST3" > /dev/null
          bash -c "$MX3" > /dev/null
          echo -e "$LINK" > mx.sh
          ./test
